baseURL = 'https://karolshirley.com'
languageCode = 'en-us'
title = 'Karol Shirley // Portfolio'
theme = "2023"

[params]
    name = "Karol Shirley"
    resume = "kshirley-resume.pdf"

    [params.contact]
        formspree_id="mknkazdg"

    [params.social]
        github = "knshirley"
        linkedin = "karolshirley"